Cope with BackupStream's normalized_backup_time being None [BF-1754]
It's hard to write a unit test for this, but with typing added (see
my other PRs) mypy will actually complain:

myhoard/controller.py:1115: error: Value of type variable "SupportsRichComparisonT" of "max" cannot be "Optional[str]"